# Generated by Django 6.0.6 on 2026-06-22 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_tag', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('omada_username', models.CharField(blank=True, max_length=255, null=True)),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('software_id', models.AutoField(primary_key=True, serialize=False)),
                ('software_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'software',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('cpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('threads', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='departments.asset')),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='departments.department'),
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('gpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('vram', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_version', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='departments.asset')),
            ],
            options={
                'db_table': 'gpu',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('motherboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bios_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboards', to='departments.asset')),
            ],
            options={
                'db_table': 'motherboard',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('network_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcp_enabled', models.BooleanField(blank=True, null=True)),
                ('current_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('port_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vlan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('omada_username', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='departments.asset')),
            ],
            options={
                'db_table': 'network',
            },
        ),
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('peripheral_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='departments.asset')),
            ],
            options={
                'db_table': 'peripherals',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('ram_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('slot_number', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rams', to='departments.asset')),
            ],
            options={
                'db_table': 'ram',
            },
        ),
        migrations.CreateModel(
            name='AssetSoftware',
            fields=[
                ('asset_software_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_installed', models.CharField(blank=True, max_length=255, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('installed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('license_type', models.CharField(blank=True, max_length=255, null=True)),
                ('license_key', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('removal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_software', to='departments.asset')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_software', to='departments.software')),
            ],
            options={
                'db_table': 'asset_software',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('interface', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='departments.asset')),
            ],
            options={
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='departments.userprofile'),
        ),
    ]
