# Generated by Django 6.0.6 on 2026-06-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('monitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='departments.asset')),
            ],
            options={
                'db_table': 'monitor',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('architecture', models.CharField(blank=True, max_length=255, null=True)),
                ('partition', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_systems', to='departments.asset')),
            ],
            options={
                'db_table': 'operating_system',
            },
        ),
        migrations.DeleteModel(
            name='AssetSoftware',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
    ]
