# Generated by Django 6.0.6 on 2026-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_monitor_operatingsystem_delete_assetsoftware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
