# Generated by Django 6.0.6 on 2026-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_asset_asset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='chassis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
