# Generated by Django 6.0.6 on 2026-06-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_motherboard_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
