# Generated by Django 6.0.6 on 2026-06-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_asset_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='dhcp_enabled',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
